#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	// reset all motor encoder values
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(armMotor);
	sensorReset(S3);

	// Move forward until object is within 2cm
	while (getUSDistance(sonarSensor) > 3) {
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
	}

	//stop robot
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	// bring robot arm down
	setMotorTarget(armMotor, -100, 50);
	//waitUntilMotorStop(armMotor);

	//move robot towards the line
	setMotorTarget(leftMotor, 550, 20);
	setMotorTarget(rightMotor, 550, 20);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	while(getMotorEncoder(leftMotor) < 7000){
		//Drift left
		setMotorSpeed(rightMotor, 20);
		setMotorSpeed(leftMotor, 0);

		//Do you see the line?
		//If yes, drift right, if not go back to drifting left
		while(getColorReflected(colorSensor) < 20) {
			//If the robot sees the line, drift right
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 20);
		}
	}

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	setMotorTarget(leftMotor, 200, 20);
	setMotorTarget(rightMotor, 200, 20);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	playSound(soundBeepBeep);

	//stop robot at the end of the line, in the red target zone
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	//bring arm up, releasing box
	setMotorTarget(armMotor, 100, 50);
	waitUntilMotorStop(armMotor);
}
