#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// reset all motor encoder values
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(armMotor);

	// Move forward until object is within 2cm
	while (getUSDistance(sonarSensor) > 3) {
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
	}

	//stop robot
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	// bring robot arm down
	setMotorTarget(armMotor, -100, 50);
	//waitUntilMotorStop(armMotor);

	//move robot towards the line
	setMotorTarget(leftMotor, 300, 20);
	setMotorTarget(rightMotor, 300, 20);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	sensorReset(S3);

	int right_Motor_Encoder = 200;
	// drift left
	while(getMotorEncoder(rightMotor) < right_Motor_Encoder){
		setMotorSpeed(rightMotor, 20);
		setMotorSpeed(leftMotor, 0);

		// if you see the line, drift right and set the target encoder value to the end of the route
		while(getColorReflected(S3) < 5) {
			setMotorSpeed(leftMotor, 20);
			setMotorSpeed(rightMotor, 0);
			right_Motor_Encoder = 6000;
		}
	}


	// if the line was on your left and followed to the end, commence end sequence
	if(getMotorEncoder(rightMotor) >= 6000){
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);

		// move robot into red square
		setMotorTarget(leftMotor, 200, 20);
		setMotorTarget(rightMotor, 200, 20);
		waitUntilMotorStop(rightMotor);
		waitUntilMotorStop(leftMotor);

		// stop robot in the red target zone
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
		waitUntilMotorStop(rightMotor);
		waitUntilMotorStop(leftMotor);

		// bring arm up, releasing box
		setMotorTarget(armMotor, 100, 50);
		waitUntilMotorStop(armMotor);

		//playSound(soundBlip);
	}
	else{

		// drift right to get back to center
		setMotorTarget(rightMotor, 0, 20);
		setMotorTarget(leftMotor, 100, 20);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);

		int left_Motor_Encoder = 2000;
		// if you dont see the line to your left, drift right
		while(getMotorEncoder(leftMotor) < left_Motor_Encoder){
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 20);

			// if you see the line, drift left and set the target encoder value to the end of the route
			while(getColorReflected(colorSensor) < 5) {
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 20);
				left_Motor_Encoder = 6000;
			}
		}

		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);

		// move robot into red square
		setMotorTarget(leftMotor, 200, 20);
		setMotorTarget(rightMotor, 200, 20);
		waitUntilMotorStop(rightMotor);
		waitUntilMotorStop(leftMotor);

		// stop robot in the red target zone
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
		waitUntilMotorStop(rightMotor);
		waitUntilMotorStop(leftMotor);

		// bring arm up, releasing box
		setMotorTarget(armMotor, 100, 50);
		waitUntilMotorStop(armMotor);

	}

}
